name: make ipa

on:
  workflow_dispatch:
  
jobs:
  build_site:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew install make gcc@12 mingw-w64 imagemagick

      - name: Install SDL2
        run: |
          git clone -b SDL2 https://github.com/libsdl-org/SDL.git SDL2
          cp -a SDL2/include include/
          mv include/include include/SDL2
          
      - name: Build
        run: |
          cd tools
          make
          cd ..
          chmod +x build_ios.sh
          ./build_ios.sh iphoneos arm64 output.ipa
          
      - name: Package IPA
        run: |
          cd sm64ios
          chmod +x generate_ipa.sh
          ./generate_ipa.sh iphoneos arm64 output.ipa
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
          path: build
